/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Conexion.Contacto;
import Conexion.Tarea;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andre
 */
public class TareaFrame extends javax.swing.JFrame {

    /**
     * Creates new form Tarea
     */
    public TareaFrame() {
        initComponents();
        loadTable();
        this.loadComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        agregarTarea = new javax.swing.JButton();
        nombreTarea = new javax.swing.JTextField();
        entregaTarea = new javax.swing.JTextField();
        fechaTarea = new javax.swing.JTextField();
        buscarContacto = new javax.swing.JButton();
        editarContacto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableContactos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        contactos = new javax.swing.JComboBox<>();
        estadoTarea = new javax.swing.JComboBox<>();
        idTarea = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TAREAS");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ENTREGA:");

        agregarTarea.setText("AGREGAR");
        agregarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarTareaActionPerformed(evt);
            }
        });

        nombreTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTareaActionPerformed(evt);
            }
        });

        buscarContacto.setText("BUSCAR");
        buscarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarContactoActionPerformed(evt);
            }
        });

        editarContacto.setText("ACTUALIZAR");
        editarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarContactoActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ESTADO:");

        tableContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableContactos);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRE: ");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FECHA");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CONTACTO:");

        contactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactosActionPerformed(evt);
            }
        });

        estadoTarea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        estadoTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoTareaActionPerformed(evt);
            }
        });

        idTarea.setEnabled(false);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(estadoTarea, 0, 267, Short.MAX_VALUE)
                            .addComponent(contactos, 0, 267, Short.MAX_VALUE)
                            .addComponent(idTarea))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(buscarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(entregaTarea, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                .addComponent(nombreTarea)
                                .addComponent(fechaTarea, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(agregarTarea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(editarContacto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(92, 92, 92)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(estadoTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(contactos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(idTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(nombreTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(agregarTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(buscarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(2, 2, 2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(fechaTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(16, 16, 16)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(entregaTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(editarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(44, 44, 44))
                        .addComponent(jLabel5))
                    .addContainerGap(321, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarTareaActionPerformed
        // TODO add your handling code here:

        String URL = "jdbc:mysql://localhost:3306/mydb?useSSL=false&serveTimezone=UTC";
        String USER = "root";
        String PASSWORD = "password123";
        Tarea tarea = new Tarea(URL, USER, PASSWORD); 

    
        tarea.insert(nombreTarea.getText(), fechaTarea.getText(), entregaTarea.getText(),String.valueOf(estadoTarea.getSelectedItem()), Integer.parseInt((String) contactos.getSelectedItem()));
        loadTable();
        JOptionPane.showMessageDialog(null, "Tarea agregada con exito");
        
        nombreTarea.setText("");
        fechaTarea.setText("");
        entregaTarea.setText("");
        estadoTarea.setSelectedIndex(0);
        contactos.setSelectedIndex(0);
        
   
    }//GEN-LAST:event_agregarTareaActionPerformed

    private void buscarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarContactoActionPerformed
        // TODO add your handling code here:

        String idUpdate = JOptionPane.showInputDialog("Ingrese el ID del contacto a actualizar");
        String URL = "jdbc:mysql://localhost:3306/mydb?useSSL=false&serveTimezone=UTC";
        String USER = "root";
        String PASSWORD = "password123";
        Tarea tareaById = new Tarea(URL, USER, PASSWORD);
        String[] tarea = tareaById.getTareaById(Integer.parseInt(idUpdate)); 

        idTarea.setText(tarea[0]);
        nombreTarea.setText(tarea[1]);
        fechaTarea.setText(tarea[2]);
        entregaTarea.setText(tarea[3]);
        estadoTarea.setSelectedItem(tarea[4]);
        contactos.setSelectedIndex(Integer.parseInt(tarea[5]));

    }//GEN-LAST:event_buscarContactoActionPerformed

    private void editarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarContactoActionPerformed
        // TODO add your handling code here:
        String URL = "jdbc:mysql://localhost:3306/mydb?useSSL=false&serveTimezone=UTC";
        String USER = "root";
        String PASSWORD = "password123";
        Contacto con = new Contacto(URL, USER, PASSWORD);

         Tarea tarea = new Tarea(URL, USER, PASSWORD); 

    
        tarea.insert(nombreTarea.getText(), fechaTarea.getText(), entregaTarea.getText(),String.valueOf(estadoTarea.getSelectedItem()), Integer.parseInt((String) contactos.getSelectedItem()));
   
        loadTable();
        JOptionPane.showMessageDialog(rootPane, "CAMPO ACTUALIZADO");
        nombreTarea.setText("");
        fechaTarea.setText("");
        entregaTarea.setText("");
        estadoTarea.setSelectedIndex(0);
        contactos.setSelectedIndex(0);
    }//GEN-LAST:event_editarContactoActionPerformed

    private void nombreTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTareaActionPerformed

    private void contactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactosActionPerformed

    private void estadoTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoTareaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TareaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TareaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TareaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TareaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TareaFrame().setVisible(true);
            }
        });
    }
    
    public void loadComboBox() { 
        String URL = "jdbc:mysql://localhost:3306/mydb?useSSL=false&serveTimezone=UTC";
        String USER = "root"; 
        String PASSWORD = "password123";
        Contacto con = new Contacto(URL, USER, PASSWORD);
        
        List<String[]> contactosAll = new ArrayList<>(); 
        
        contactosAll = con.getAllContacts(); 
        
        for(String[] fila: contactosAll) {
            contactos.addItem(fila[0]);
        }
        
    }
    
    public void loadTable() { 
        String URL = "jdbc:mysql://localhost:3306/mydb?useSSL=false&serveTimezone=UTC";
        String USER = "root"; 
        String PASSWORD = "password123";
        Tarea tarea = new Tarea(URL, USER, PASSWORD); 
        DefaultTableModel modelo = new DefaultTableModel();
        List<String[]> tareas = new ArrayList<>(); 
        modelo.addColumn("IDO"); 
        modelo.addColumn("NOMBRE");
        modelo.addColumn("FECHA");
        modelo.addColumn("ENTREGA");
        modelo.addColumn("ESTADO");
        modelo.addColumn("CONTACTO");
        tareas = tarea.getAllTasks(); 
        for(String[] fila : tareas) { 
            modelo.addRow(fila);
        }
        
        this.tableContactos.setModel(modelo );
 
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarTarea;
    private javax.swing.JButton buscarContacto;
    private javax.swing.JComboBox<String> contactos;
    private javax.swing.JButton editarContacto;
    private javax.swing.JTextField entregaTarea;
    private javax.swing.JComboBox<String> estadoTarea;
    private javax.swing.JTextField fechaTarea;
    private javax.swing.JTextField idTarea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreTarea;
    private javax.swing.JTable tableContactos;
    // End of variables declaration//GEN-END:variables
}
